blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [
    path("", views.all_posts, name="all_posts"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("<str:category>/", views.category, name="category"),
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),
]

projects/urls.py
from django.urls import path
from projects import views


app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name="all_projects"),
    path('<int:pk>', views.project_detail, name="project_detail"),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
        return self.title[:50]


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

projects/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

    def __str__(self):
        return self.title[:50]

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(max_length=60,
                             widget=forms.TextInput(attrs={
                                 "class": "form-control",
                                 "placeholder": "Your Name",
                             }))
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!",
        }))

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from .forms import CommentForm


def all_posts(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    return render(request, "blog/all_posts.html", context)


def category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category).order_by('-created_on')
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog/category.html", context)


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
                )
            comment.save()

    comments = Comment.objects.filter(post=post)
    form = CommentForm()

    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog/detail.html", context)

projects/views.py
from django.shortcuts import render
from projects.models import Project


# Create your views here.
def all_projects(request):
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html',
                  {'projects': projects})


def project_detail(request, pk):
    project = Project.objects.get(pk=pk)

    return render(request, 'projects/detail.html',
                  {'project': project,
                   })

blog/templates/blog/all_posts.html
{% extends 'projects/base.html' %}

{% block content %}

<div class="col-md_8 offset-md-2">
	<h1>Blog Index</h1>
	<hr>
	{% for post in posts %}
	<h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
	<small>
		{{ post.created_on.date }} |&nbsp;
		Categories:&nbsp;
		{% for category in post.categories.all %}
		<a href="{% url 'blog:category' category.name %}">
			{{ category.name }}
		</a>&nbsp;
		{% endfor %}
	</small>
	<p>{{ post.body | slice:":400" }}...</p>
	{% endfor %}
</div>

{% endblock %}

blog/templates/blog/category.html
{% extends 'projects/base.html' %}

{% block content %}

<div class="col-md_8 offset-md-2">
	<h1>{{ category | title }}</h1>
	<hr>
	{% for post in posts %}
	<h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
	<small>
		{{ post.created_on.date }} |&nbsp;
		Categories:&nbsp;
		{% for category in post.categories.all %}
		<a href="{% url 'blog:category' category.name %}">
			{{ category.name }}
		</a>&nbsp;
		{% endfor %}
	</small>
	<p>{{ post.body | slice:"400" }}...</p>
	{% endfor %}
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'projects/base.html' %}

{% block content %}


<div class="col-md-8 offset-md-2">
	<h1>{{ post.title }}</h1>
	<small>
		{{ post.created_on.date }} |&nbsp;
		Categories:&nbsp;
		{% for category in post.categories.all %}
		<a href="{% url 'blog:category' category.name %}">
			{{ category.name }}
		</a>&nbsp;
		{% endfor %}
	</small>
	<p>{{ post.body | linebreaks }}</p>
	<h3>Leave a comment:</h3>
	<form action="/blog/{{ post.pk }}/" method="post">
		{% csrf_token %}
		<div class="form-group">
			{{ form.author }}
		</div>
		<div class="form-group">
			{{ form.body }}
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	<h3>Comments:</h3>
	{% for comment in comments %}
	<p>
		On {{ comment.created_on.date }}&nbsp;
		<b>{{ comment.author }}</b> wrote:
	</p>
	<p>{{ comment.body }}</p>
	<hr>
	{% endfor %}
</div>

{% endblock %}

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Portfolio</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
		<a class="navbar-brand" href="{% url 'projects:all_projects' %}">Portfolio</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'projects:all_projects' %}">Home<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'blog:all_posts' %}">Blog<span class="sr-only">(current)</span></a>
			</li>
		</ul>
	</div>
  </div>
</nav>

<div class="container">
	{% block content %}

	{% endblock %}
</div>

</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}


<h1>{{ project.title }}</h1>
<div class="row">
	<div class="col-md-8">
		<img src="{% static project.image %}" alt="{{ project.description }}" width="100%">
	</div>
	<div class="col-md-4">
		<h5>About the project</h5>
		<p>{{ project.description }}</p>
		<h5>Built with:</h5>
		<p>{{ project.technology }}</p>
	</div>


{% endblock %}